version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: authen_service_db
    ports:
      - 30001:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 30122002
    networks:
      - toursaas
networks:
  toursaas:
